### ISSUE TITLE
Workshop: Decentralizing the Internet with the Polkadot

### ISSUE THREAD

**Issue by chungquantin** [openguild-labs/workshops#4]
## General Information

| Field name | Description | Field value |
| ------------- | ------ | ------------- |
| Title | Official name of the workshop | _Decentralizing the Internet with the Polkadot_ |
| Host | Name of the main host | Tin Chung |
| Partners | Are there any external partners? | --- |
| Speakers | List of speaker names | Tin |
| Description | Brief summary of the workshop content | Applying the CEHV's Blockchain OSI Model to analyze the current state of Polkadot impacts on the Internet |
| Language | Which is the delivered language of the workshop? | English |
| Date | When will it happen? | --/--/2024 |
| Mode | Offline or Online | Offline, Online |
| Participants | Number of expected participants | - |
| Applied For | | Offline Workshop, Community Call |

## Agenda

Provide the overall agenda of the workshop here

### Pre activites

- [x] Section Required

- Introducing about OpenGuild Membership system and OpenGuild Contribution Program (Technical Fellowship) 
- Why OpenGuild choose Rust as the focused programming language?

### Main activities

- [x] Section Required 

#### List of deliverables
- [x] Slides

#### Detailed plan

| Section name| Description | Speaker / Guest |
| ------------- | ------ | ------------- |
| --- | --- | Tin |

### Post activities

Onboarding the audience to OpenGuild community.

**Comment by NTP-996** [comment]
Here is the slide for this workshop: https://www.canva.com/design/DAGF8Bq8rGw/eHtg36i-8Un1v9jFUZyvUg/edit
