### ISSUE TITLE
Workshop: Peer-to-peer Network and Why it is the END GAME of the Internet? 

### ISSUE THREAD

**Issue by chungquantin** [openguild-labs/workshops#5]
## General Information

| Field name | Description | Field value |
| ------------- | ------ | ------------- |
| Title | Official name of the workshop | _Peer-to-peer Network and Why it is the END GAME of the Internet?_ |
| Host | Name of the main host | Tin Chung |
| Partners | Are there any external partners? | --- |
| Speakers | List of speaker names | Tin |
| Description | Brief summary of the workshop content | Applying the CEHV's Blockchain OSI Model to analyze the current state of Polkadot impacts on the Internet |
| Language | Which is the delivered language of the workshop? | English |
| Date | When will it happen? | --/--/2024 |
| Mode | Offline or Online | Offline, Online |
| Participants | Number of expected participants | - |
| Applied For | | Offline Workshop, Community Call |

## Agenda

Provide the overall agenda of the workshop here

### Pre activites

- [x] Section Required

- Introducing about OpenGuild Membership system and OpenGuild Contribution Program (Technical Fellowship) 
- Why OpenGuild choose Rust as the focused programming language?

### Main activities

- [x] Section Required 

#### List of deliverables
- [x] Slides

#### Detailed plan

| Section name| Description | Speaker / Guest |
| ------------- | ------ | ------------- |
| --- | --- | Tin |

### Post activities

Onboarding the audience to OpenGuild community.

**Comment by NTP-996** [comment]
@chungquantin here are the slides (https://docs.google.com/presentation/d/1BwF9S-9yupsu-Pa-zL-VFCDvfTSdALv_3xToeip-9eQ/edit?usp=sharing)
I think you can change it from `the END GAME` to something like `the step in the internet evolution` It's not the end game, because it still evolving

**Comment by NTP-996** [comment]
The slide for this workshop: https://docs.google.com/presentation/d/1LYUFg24_jfVGXO5t1kf3y2llRqNTslbw40jkvFhz8f8/edit?usp=sharing
