### ISSUE TITLE
Workshop: Building a NFT blockchain with Substrate Kitties

### ISSUE THREAD

**Issue by chungquantin** [openguild-labs/workshops#9]

**Comment by NTP-996** [comment]
Here is the slide of the workshop: https://docs.google.com/presentation/d/174UT4GGYxFEi-wcw8zhFP9niv3lggf3A2kgJEkCaNfE/edit?usp=sharing

**Comment by chungquantin** [comment]
@NTP-996 Please don't reinvent the wheel. I think we already had good slides for Substrate here: https://docs.google.com/presentation/d/1ZfwjoB_nMrqLN3OtY_hLSewwnkLJ8V6WtVQ0hJGm3SI/edit#slide=id.g26689998dcb_0_448

So please reuse it and make more slides for Substrate Kitties, the core part of the workshop not trying to break down Substrate again.

**Comment by NTP-996** [comment]
@chungquantin sure I will reuse the old slide

**Comment by NTP-996** [comment]
here the full silde https://docs.google.com/presentation/d/1vPX5mwvvIAJ7tkIxA43GN6jkPg9iRLW_kGtPOqxBY4Y/edit?usp=sharing
